# Generated by Django 3.1.4 on 2021-02-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20, verbose_name='Date')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('cases', models.CharField(max_length=2, verbose_name='Cases')),
                ('deaths', models.CharField(max_length=12, verbose_name='Deaths')),
                ('lethality', models.CharField(max_length=1, verbose_name='Lethality')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Region',
                'ordering': ['name'],
            },
        ),
    ]
